### ISSUE TITLE
bam_filter and count_reads broken by API update

### ISSUE THREAD

**Issue by filidi** [brentp/hts-nim-tools#4]
record.qual was deprecated in hts-nim in favor of record.mapping_quality (https://github.com/brentp/hts-nim/issues/14), which requires updates to bam_filter and count_reads. That's the only fix it takes to compile, but are there other field renames that affect these tools?

**Comment by brentp** [comment]
Thanks for pointing this out. That's all the change that's required. Please let me know any other issues.
