### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by pengyu1608** [brentp/hts-nim-tools#7]
Hi, I tried to install hts-nim-tools.  My operating system is CentOS 7.2.

My procedure:

curl https://nim-lang.org/choosenim/init.sh -sSf | sh
export PATH=$PATH:$HOME/.nimble/bin

nimble install -y https://github.com/brentp/hts-nim-tools --nimbleDir:$HOME/.nimble

Downloading https://github.com/brentp/hts-nim-tools using git
  Verifying dependencies for hts_nim_tools@0.1.5
      Info: Dependency on c2nim@>= 0.9.10 already satisfied
  Verifying dependencies for c2nim@0.9.14
      Info: Dependency on docopt@any version already satisfied
  Verifying dependencies for docopt@0.6.8
      Info: Dependency on regex@>= 0.7.4 already satisfied
  Verifying dependencies for regex@0.12.0
      Info: Dependency on unicodedb@>= 0.7.2 already satisfied
  Verifying dependencies for unicodedb@0.7.2
      Info: Dependency on unicodeplus@>= 0.5.0 already satisfied
  Verifying dependencies for unicodeplus@0.5.1
      Info: Dependency on unicodedb@>= 0.7 already satisfied
  Verifying dependencies for unicodedb@0.7.2
      Info: Dependency on lapper@any version already satisfied
  Verifying dependencies for lapper@0.1.4
      Info: Dependency on hts@any version already satisfied
  Verifying dependencies for hts@0.2.21
      Info: Dependency on kexpr@any version already satisfied
  Verifying dependencies for kexpr@0.0.2
 Installing hts_nim_tools@0.1.5
   Building hts_nim_tools/hts_nim_tools using c backend
Error: Build failed for package: hts_nim_tools
        ... Details:
        ... Execution failed with exit code 1
        ... Command: "/home/yupeng/.nimble/bin/nim" c --noBabelPath -d:release --path:"/home/yupeng/.nimble/pkgs/c2nim-0.9.14"  --path:"/home/yupeng/.nimble/pkgs/docopt-0.6.8"  --path:"/home/yupeng/.nimble/pkgs/regex-0.12.0"  --path:"/home/yupeng/.nimble/pkgs/unicodedb-0.7.2"  --path:"/home/yupeng/.nimble/pkgs/unicodeplus-0.5.1"  --path:"/home/yupeng/.nimble/pkgs/unicodedb-0.7.2"  --path:"/home/yupeng/.nimble/pkgs/lapper-0.1.4"  --path:"/home/yupeng/.nimble/pkgs/hts-0.2.21"  --path:"/home/yupeng/.nimble/pkgs/kexpr-0.0.2"  -o:"/tmp/nimble_39277/githubcom_brentphtsnimtools/hts_nim_tools" "/tmp/nimble_39277/githubcom_brentphtsnimtools/src/hts_nim_tools.nim"
        ... Output: Hint: used config file '/home/yupeng/.choosenim/toolchains/nim-0.20.2/config/nim.cfg' [Conf]

 ... Hint: util [Processing]
        ... Hint: kexpr [Processing]
        ... Hint: version [Processing]
        ... Hint: lapper [Processing]
        ... /tmp/nimble_23162/githubcom_brentphtsnimtools/src/count_reads.nim(73, 19) Error: attempting to call undeclared routine: 'querys'

**Comment by brentp** [comment]
thanks for reporiting. this was do to using a deprecated (and now removed `querys` function) I have updated the code and it works now.

**Comment by pengyu1608** [comment]
Thanks for the reply. It is solved now.



Peng Yu, Ph.D
Computational Biologist
Laboratory of Stem Cell and Epigenetics
State Key Laboratory of Cardiovascular Disease
Fuwai Hospital, Chinese Academy of Medical Science
167 Beilishi Road, Beijing, China 100037
 
From: Brent Pedersen
Date: 2019-09-18 20:17
To: brentp/hts-nim-tools
CC: Peng Yu; Author
Subject: Re: [brentp/hts-nim-tools] Installation error (#7)
thanks for reporiting. this was do to using a deprecated (and now removed querys function) I have updated the code and it works now.
