### ISSUE TITLE
Could not import: bam_hdr_destroy

### ISSUE THREAD

**Issue by pengyu1608** [brentp/hts-nim-tools#8]
Hi, when I tried to run the latest hts_nim_tools, it reports: "could not import: bam_hdr_destroy"

I searched it on the web and found the following: "Rename bam_hdr_init/_destroy/_dup() to sam_hdr_init/_destroy/_dup()" in htslib.

https://github.com/samtools/htslib/commit/58b64d83da95f6290baaa76f01d91216312ad16b

Is that the cause? Thanks.

**Comment by brentp** [comment]
hi, you'll need to use htslib 1.9 (or after 1.9 but before the commit that changed the API). i'll start a branch soon that tracks htslib devel, but i want to make sure it's stable.

**Comment by cmdcolin** [comment]
I think currently the homebrew/linuxbrew formula might run into this at the moment
commit log from homebrew formula says it updated to 1.10 in dec 2019

```
commit 3eef35543681ae89b0dbfc59c3f507ff01c5a16a
Author: BrewTestBot <homebrew-test-bot@lists.sfconservancy.org>
Date:   Sat Jan 11 20:57:59 2020 +0000

    htslib: update 1.10.2 bottle.

commit b705d726dbeb11c3d7dc783debddfc5dafa65827
Author: Caleb Xu <calebcenter@live.com>
Date:   Sat Jan 11 15:05:15 2020 -0500

    htslib 1.10.2

commit a20d2e27a8a1936110e9bd22d230c0e77210561a
Author: BrewTestBot <homebrew-test-bot@lists.sfconservancy.org>
Date:   Sun Dec 8 23:29:45 2019 +0000

    htslib: update 1.10 bottle.

commit 00147bb8cd4338cd3a587e984fc41477fca63ddc
Author: Jonathan Chang <jchang641@gmail.com>
Date:   Mon Dec 9 10:12:06 2019 +1100

    htslib 1.10

```

**Comment by cmdcolin** [comment]
(to be specific I was using mosdepth installed via linuxbrew)

**Comment by brentp** [comment]
the latest mosdepth tag (v0.2.9) will build with htslib 1.10+ (and hts-nim >= 0.3.0).

I just pushed a fix (08c5296) for this library (08c5296) to work with hts-nim >= 0.3.0.

@pengyu1608 , that should resolve your issue.

@cmdcolin let me know if using the latest mosdepth release resolve your problem.

thanks,
-Brent

**Comment by cmdcolin** [comment]
Thanks! I'll see if I can update the homebrew formula

**Comment by brentp** [comment]
great! let me know if you encounter any problems.
